default:
  image: python:latest

variables:
  DOCKER_HUB_TAG: tournament
  LOCAL_IMAGE: bot
  DOCKER_DRIVER: overlay2

stages:         
  - test
  - build
  - deploy

unit-test-job:   
  stage: test
  before_script:
    - cd bot
  script:
    - pip install pytest
    - pytest   

code_style:   
  stage: test    
  before_script:
    - cd bot
  script:
    - pip install pycodestyle
    - pycodestyle
  allow_failure: true

build-job:
  stage: build
  image: docker:latest
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  services:
    - name: docker:dind
  script:
    - cd ./bot
    - docker build -t $LOCAL_IMAGE .
    - docker tag $LOCAL_IMAGE:latest $CI_REGISTRY_USER/$DOCKER_HUB_TAG
    - docker push $CI_REGISTRY_IMAGE:latest


deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
