default:
  image: python:latest

variables:
  DOCKER_HUB_TAG: tournament
  LOCAL_IMAGE: bot
  DOCKER_DRIVER: overlay2
  LINUX_USER: ubuntu

stages:         
  - test
  - build
  - scanning
  - deploy
  - notify

unit_tests:   
  stage: test
  before_script:
    - cd bot
  script:
    - pip install pytest
    - pytest   

code_style:   
  stage: test
  before_script:
    - pip install pycodestyle    
  script:
    - pycodestyle ./bot
  allow_failure: true

build:
  stage: build
  image: docker:latest
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  services:
    - name: docker:dind
  script:
    - cd ./bot
    - docker build -t $CI_REGISTRY_USER/$DOCKER_HUB_TAG .
    - docker run -d $CI_REGISTRY_USER/$DOCKER_HUB_TAG
    - docker logs $CI_REGISTRY_USER/$DOCKER_HUB_TAG
    - docker push $CI_REGISTRY_IMAGE:latest

container_scanning:
  stage: scanning
  image: docker:latest
  services:
  - name: docker:dind
  before_script:
    - docker pull aquasec/trivy
  script:
    - docker run -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image $CI_REGISTRY_IMAGE:latest

deploy:
  image: alpine:latest
  stage: deploy 
  environment: production
  before_script:
    - apk upgrade && apk add openssh-client curl
    - eval $(ssh-agent -s)
    - chmod 400 "$SSH_KEY"
    - ssh-add "$SSH_KEY"
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
  script:
    - ssh -o StrictHostKeyChecking=no $LINUX_USER@$SERVER_IP "cd bot; git pull https://${GIT_USERNAME}:${GIT_PASSWORD}@gitlab.com/sample9832632/bot.git"
    - ssh -o StrictHostKeyChecking=no $LINUX_USER@$SERVER_IP "sudo docker pull $CI_REGISTRY_IMAGE:latest"
    - ssh -o StrictHostKeyChecking=no $LINUX_USER@$SERVER_IP "echo TELEGRAM_TOKEN=${TELEGRAM_TOKEN} > bot/bot/.env"
    - ssh -o StrictHostKeyChecking=no $LINUX_USER@$SERVER_IP "sudo docker compose -f bot/bot/docker-compose.yaml pull"
    - ssh -o StrictHostKeyChecking=no $LINUX_USER@$SERVER_IP "sudo docker compose -f bot/bot/docker-compose.yaml up -d"
  after_script:
    - sh ./bot/scripts/notify.sh "Success ✅"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

notify_error:
  stage: notify
  script:
    - apk add curl
    - sh ./bot/scripts/notify.sh "Failed ❌"
  when: on_failure