version: '2'
services:
  server:
    image: levshakovn/tournament
    ports:
      - "80:80"
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      DATABASE: tournament
    depends_on:
      - database
    container_name: bot
  database:
    image: postgres:15.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tournament
    ports:
      - "5432:5432"
    volumes:
      - /home/ubuntu/db-data:/var/lib/postgresql/data
      - ./files/init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: postgres
