version: '2'
services:
  server:
    build: .
    ports:
      - "80:80"
    depends_on:
      - database
  database:
    image: postgres
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=admin"
    ports:
      - "5432:5432"
    volumes:
      - /home/ubuntu/db-data:/var/lib/postgresql/data